version: '2'

services:

    mysqlsrv:
      container_name: "mysqlsrv"
      hostname: "mysqlsrv"
      domainname: "mysqlsrv"
      image: mysql:5.6
      volumes:
        - ./build/mysql:/etc/mysql/conf.d
      ports:
        - "3306:3306"
      expose:
        - "3306"
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: studioserviziweb

    lamp_project:

      build: ./build/apache
      container_name: "dev.studiuoserviziweb"
      depends_on:
        - mysqlsrv
      external_links:
        - mysqlsrv:mysql
      ports:
        - '80:80'
      volumes:
        - ../webroot:/var/www/html
        - ./build/apache/logs:/var/log/apache2/
      environment:
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: root
          WORDPRESS_DB_NAME: studioserviziweb
          WORDPRESS_TABLE_PREFIX: ssw_
